name: "Deploy UI"
description: "Builds and deploys a React based UI"
inputs: 
  sa_email: 
    description: "Service account email address"
    required: true
  sa_key: 
    required: true
  project_id: 
    required: true
  gs_url: 
    required: true
runs: 
  image: Dockerfile
  using: docker    
  args:
    - ${{ inputs.sa_email }}
    - ${{ inputs.sa_key }}
    - ${{ inputs.project_id }}
    - ${{ inputs.gs_url }}
